/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.2-dev */

#include "MS3000.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(RGB, RGB, AUTO)


PB_BIND(MIDI_OCTAVE, MIDI_OCTAVE, AUTO)


PB_BIND(MIDI_INTERVALS, MIDI_INTERVALS, AUTO)


PB_BIND(MIDI_STEP, MIDI_STEP, AUTO)


PB_BIND(MIDI_SEQUENCE, MIDI_SEQUENCE, AUTO)


PB_BIND(MS3KG, MS3KG, 2)


PB_BIND(MS3KG_SysPref, MS3KG_SysPref, AUTO)


PB_BIND(MS3KG_SysPref_AP_INFO, MS3KG_SysPref_AP_INFO, AUTO)


PB_BIND(MS3KG_App, MS3KG_App, 2)


PB_BIND(MS3KG_App_Shake, MS3KG_App_Shake, AUTO)


PB_BIND(MS3KG_App_Light, MS3KG_App_Light, AUTO)


PB_BIND(MS3KG_App_Magnet, MS3KG_App_Magnet, AUTO)


PB_BIND(MS3KG_App_System, MS3KG_App_System, AUTO)


PB_BIND(MS3KG_App_Remote, MS3KG_App_Remote, AUTO)


PB_BIND(MS3KG_App_Beat, MS3KG_App_Beat, AUTO)


PB_BIND(MS3KG_App_Countdown, MS3KG_App_Countdown, AUTO)


PB_BIND(MS3KG_App_Arpi, MS3KG_App_Arpi, AUTO)


PB_BIND(MS3KG_App_Sequi, MS3KG_App_Sequi, AUTO)


PB_BIND(MS3KG_App_Updater, MS3KG_App_Updater, AUTO)










