/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.2-dev */

#ifndef PB_MS3000_PB_H_INCLUDED
#define PB_MS3000_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _MS3KG_App_T {
    MS3KG_App_T__Shake = 0,
    MS3KG_App_T__Light = 1,
    MS3KG_App_T__Magnet = 2,
    MS3KG_App_T__System = 3,
    MS3KG_App_T__Remote = 4,
    MS3KG_App_T__Beat = 5,
    MS3KG_App_T__Countdown = 6,
    MS3KG_App_T__Arpi = 7,
    MS3KG_App_T__Sequi = 8
} MS3KG_App_T;

typedef enum _MS3KG_App_Light_Mode {
    MS3KG_App_Light_Mode_RAINBOW = 0,
    MS3KG_App_Light_Mode_NORMAL = 1,
    MS3KG_App_Light_Mode_SCANNER_RGB = 2,
    MS3KG_App_Light_Mode_SCANNER_BW = 3
} MS3KG_App_Light_Mode;

typedef enum _MS3KG_App_Magnet_Mode {
    MS3KG_App_Magnet_Mode_BARS = 0,
    MS3KG_App_Magnet_Mode_BARS_DOT = 1,
    MS3KG_App_Magnet_Mode_DOTS = 2,
    MS3KG_App_Magnet_Mode_OTHER = 3
} MS3KG_App_Magnet_Mode;

typedef enum _MS3KG_App_System_Mode {
    MS3KG_App_System_Mode_VERSION = 0,
    MS3KG_App_System_Mode_WIFI = 1,
    MS3KG_App_System_Mode_SSID = 2,
    MS3KG_App_System_Mode_IP = 3,
    MS3KG_App_System_Mode_SOFTIP = 4,
    MS3KG_App_System_Mode_POWER_LO = 5,
    MS3KG_App_System_Mode_POWER_HI = 6,
    MS3KG_App_System_Mode_POWER_VALUE = 7,
    MS3KG_App_System_Mode_CALIBRATION = 8
} MS3KG_App_System_Mode;

typedef enum _MS3KG_App_Beat_Mode {
    MS3KG_App_Beat_Mode_SIDE = 0,
    MS3KG_App_Beat_Mode_CENTER = 1
} MS3KG_App_Beat_Mode;

typedef enum _MS3KG_App_Countdown_Mode {
    MS3KG_App_Countdown_Mode_DOWN_1S = 0,
    MS3KG_App_Countdown_Mode_DOWN_5S = 1,
    MS3KG_App_Countdown_Mode_DOWN_10S = 2,
    MS3KG_App_Countdown_Mode_DOWN_30S = 3,
    MS3KG_App_Countdown_Mode_DOWN_1M = 4,
    MS3KG_App_Countdown_Mode_DOWN_5M = 5,
    MS3KG_App_Countdown_Mode_DOWN_10M = 6,
    MS3KG_App_Countdown_Mode_DOWN_30M = 7
} MS3KG_App_Countdown_Mode;

typedef enum _MS3KG_App_Arpi_Mode {
    MS3KG_App_Arpi_Mode_ARP1 = 0,
    MS3KG_App_Arpi_Mode_ARP2 = 1,
    MS3KG_App_Arpi_Mode_ARP3 = 2,
    MS3KG_App_Arpi_Mode_ARP4 = 3,
    MS3KG_App_Arpi_Mode_ARP5 = 4,
    MS3KG_App_Arpi_Mode_ARP6 = 5,
    MS3KG_App_Arpi_Mode_ARP7 = 6,
    MS3KG_App_Arpi_Mode_ARP8 = 7
} MS3KG_App_Arpi_Mode;

/* Struct definitions */
typedef struct _MS3KG_App_Remote {
    char dummy_field;
} MS3KG_App_Remote;

typedef struct _MS3KG_SysPref {
    char dummy_field;
} MS3KG_SysPref;

typedef struct _MS3KG_SysPref_AP_INFO {
    pb_callback_t networkName;
    pb_callback_t password;
} MS3KG_SysPref_AP_INFO;

typedef struct _MIDI_INTERVALS {
    int32_t v;
} MIDI_INTERVALS;

typedef struct _MIDI_OCTAVE {
    int32_t o;
} MIDI_OCTAVE;

typedef struct _MS3KG_App_Arpi {
    bool has_mode;
    MS3KG_App_Arpi_Mode mode;
} MS3KG_App_Arpi;

typedef struct _MS3KG_App_Countdown {
    bool has_mode;
    MS3KG_App_Countdown_Mode mode;
} MS3KG_App_Countdown;

typedef struct _MS3KG_App_Magnet {
    bool has_mode;
    MS3KG_App_Magnet_Mode mode;
} MS3KG_App_Magnet;

typedef struct _MS3KG_App_Shake {
    pb_callback_t image;
    bool has_colorIndex;
    int32_t colorIndex;
    bool has_bounce;
    int32_t bounce;
} MS3KG_App_Shake;

typedef struct _MS3KG_App_System {
    bool has_mode;
    MS3KG_App_System_Mode mode;
} MS3KG_App_System;

typedef struct _MS3KG_App_Updater {
    bool has_shouldReset;
    int32_t shouldReset;
} MS3KG_App_Updater;

typedef struct _RGB {
    int32_t R;
    int32_t G;
    int32_t B;
} RGB;

typedef struct _MIDI_STEP {
    MIDI_INTERVALS interval;
    MIDI_OCTAVE octave;
    int32_t mode;
} MIDI_STEP;

typedef struct _MS3KG_App_Beat {
    bool has_mode;
    MS3KG_App_Beat_Mode mode;
    bool has_sensitivity;
    int32_t sensitivity;
    bool has_color;
    RGB color;
} MS3KG_App_Beat;

typedef struct _MS3KG_App_Light {
    bool has_mode;
    MS3KG_App_Light_Mode mode;
    bool has_color;
    RGB color;
    bool has_colorIndex;
    int32_t colorIndex;
    bool has_triggerSpeed;
    int32_t triggerSpeed;
} MS3KG_App_Light;

typedef struct _MIDI_SEQUENCE {
    pb_size_t steps_count;
    MIDI_STEP steps[8];
} MIDI_SEQUENCE;

typedef struct _MS3KG_App_Sequi {
    bool has_sequence;
    MIDI_SEQUENCE sequence;
} MS3KG_App_Sequi;

typedef struct _MS3KG_App {
    bool has_current;
    MS3KG_App_T current;
    bool has_shake;
    MS3KG_App_Shake shake;
    bool has_light;
    MS3KG_App_Light light;
    bool has_magnet;
    MS3KG_App_Magnet magnet;
    bool has_system;
    MS3KG_App_System system;
    bool has_remote;
    MS3KG_App_Remote remote;
    bool has_beat;
    MS3KG_App_Beat beat;
    bool has_countdown;
    MS3KG_App_Countdown countdown;
    bool has_arpi;
    MS3KG_App_Arpi arpi;
    bool has_sequi;
    MS3KG_App_Sequi sequi;
    bool has_updater;
    MS3KG_App_Updater updater;
} MS3KG_App;

typedef struct _MS3KG {
    bool has_apps;
    MS3KG_App apps;
} MS3KG;


/* Helper constants for enums */
#define _MS3KG_App_T_MIN MS3KG_App_T__Shake
#define _MS3KG_App_T_MAX MS3KG_App_T__Sequi
#define _MS3KG_App_T_ARRAYSIZE ((MS3KG_App_T)(MS3KG_App_T__Sequi+1))

#define _MS3KG_App_Light_Mode_MIN MS3KG_App_Light_Mode_RAINBOW
#define _MS3KG_App_Light_Mode_MAX MS3KG_App_Light_Mode_SCANNER_BW
#define _MS3KG_App_Light_Mode_ARRAYSIZE ((MS3KG_App_Light_Mode)(MS3KG_App_Light_Mode_SCANNER_BW+1))

#define _MS3KG_App_Magnet_Mode_MIN MS3KG_App_Magnet_Mode_BARS
#define _MS3KG_App_Magnet_Mode_MAX MS3KG_App_Magnet_Mode_OTHER
#define _MS3KG_App_Magnet_Mode_ARRAYSIZE ((MS3KG_App_Magnet_Mode)(MS3KG_App_Magnet_Mode_OTHER+1))

#define _MS3KG_App_System_Mode_MIN MS3KG_App_System_Mode_VERSION
#define _MS3KG_App_System_Mode_MAX MS3KG_App_System_Mode_CALIBRATION
#define _MS3KG_App_System_Mode_ARRAYSIZE ((MS3KG_App_System_Mode)(MS3KG_App_System_Mode_CALIBRATION+1))

#define _MS3KG_App_Beat_Mode_MIN MS3KG_App_Beat_Mode_SIDE
#define _MS3KG_App_Beat_Mode_MAX MS3KG_App_Beat_Mode_CENTER
#define _MS3KG_App_Beat_Mode_ARRAYSIZE ((MS3KG_App_Beat_Mode)(MS3KG_App_Beat_Mode_CENTER+1))

#define _MS3KG_App_Countdown_Mode_MIN MS3KG_App_Countdown_Mode_DOWN_1S
#define _MS3KG_App_Countdown_Mode_MAX MS3KG_App_Countdown_Mode_DOWN_30M
#define _MS3KG_App_Countdown_Mode_ARRAYSIZE ((MS3KG_App_Countdown_Mode)(MS3KG_App_Countdown_Mode_DOWN_30M+1))

#define _MS3KG_App_Arpi_Mode_MIN MS3KG_App_Arpi_Mode_ARP1
#define _MS3KG_App_Arpi_Mode_MAX MS3KG_App_Arpi_Mode_ARP8
#define _MS3KG_App_Arpi_Mode_ARRAYSIZE ((MS3KG_App_Arpi_Mode)(MS3KG_App_Arpi_Mode_ARP8+1))


/* Initializer values for message structs */
#define RGB_init_default                         {255, 121, 0}
#define MIDI_OCTAVE_init_default                 {5}
#define MIDI_INTERVALS_init_default              {0}
#define MIDI_STEP_init_default                   {MIDI_INTERVALS_init_default, MIDI_OCTAVE_init_default, 0}
#define MIDI_SEQUENCE_init_default               {0, {MIDI_STEP_init_default, MIDI_STEP_init_default, MIDI_STEP_init_default, MIDI_STEP_init_default, MIDI_STEP_init_default, MIDI_STEP_init_default, MIDI_STEP_init_default, MIDI_STEP_init_default}}
#define MS3KG_init_default                       {false, MS3KG_App_init_default}
#define MS3KG_SysPref_init_default               {0}
#define MS3KG_SysPref_AP_INFO_init_default       {{{NULL}, NULL}, {{NULL}, NULL}}
#define MS3KG_App_init_default                   {false, _MS3KG_App_T_MIN, false, MS3KG_App_Shake_init_default, false, MS3KG_App_Light_init_default, false, MS3KG_App_Magnet_init_default, false, MS3KG_App_System_init_default, false, MS3KG_App_Remote_init_default, false, MS3KG_App_Beat_init_default, false, MS3KG_App_Countdown_init_default, false, MS3KG_App_Arpi_init_default, false, MS3KG_App_Sequi_init_default, false, MS3KG_App_Updater_init_default}
#define MS3KG_App_Shake_init_default             {{{NULL}, NULL}, false, 0, false, 0}
#define MS3KG_App_Light_init_default             {false, MS3KG_App_Light_Mode_RAINBOW, false, RGB_init_default, false, 0, false, 0}
#define MS3KG_App_Magnet_init_default            {false, MS3KG_App_Magnet_Mode_BARS}
#define MS3KG_App_System_init_default            {false, MS3KG_App_System_Mode_VERSION}
#define MS3KG_App_Remote_init_default            {0}
#define MS3KG_App_Beat_init_default              {false, MS3KG_App_Beat_Mode_SIDE, false, 2, false, RGB_init_default}
#define MS3KG_App_Countdown_init_default         {false, MS3KG_App_Countdown_Mode_DOWN_1M}
#define MS3KG_App_Arpi_init_default              {false, MS3KG_App_Arpi_Mode_ARP8}
#define MS3KG_App_Sequi_init_default             {false, MIDI_SEQUENCE_init_default}
#define MS3KG_App_Updater_init_default           {false, 0}
#define RGB_init_zero                            {0, 0, 0}
#define MIDI_OCTAVE_init_zero                    {0}
#define MIDI_INTERVALS_init_zero                 {0}
#define MIDI_STEP_init_zero                      {MIDI_INTERVALS_init_zero, MIDI_OCTAVE_init_zero, 0}
#define MIDI_SEQUENCE_init_zero                  {0, {MIDI_STEP_init_zero, MIDI_STEP_init_zero, MIDI_STEP_init_zero, MIDI_STEP_init_zero, MIDI_STEP_init_zero, MIDI_STEP_init_zero, MIDI_STEP_init_zero, MIDI_STEP_init_zero}}
#define MS3KG_init_zero                          {false, MS3KG_App_init_zero}
#define MS3KG_SysPref_init_zero                  {0}
#define MS3KG_SysPref_AP_INFO_init_zero          {{{NULL}, NULL}, {{NULL}, NULL}}
#define MS3KG_App_init_zero                      {false, _MS3KG_App_T_MIN, false, MS3KG_App_Shake_init_zero, false, MS3KG_App_Light_init_zero, false, MS3KG_App_Magnet_init_zero, false, MS3KG_App_System_init_zero, false, MS3KG_App_Remote_init_zero, false, MS3KG_App_Beat_init_zero, false, MS3KG_App_Countdown_init_zero, false, MS3KG_App_Arpi_init_zero, false, MS3KG_App_Sequi_init_zero, false, MS3KG_App_Updater_init_zero}
#define MS3KG_App_Shake_init_zero                {{{NULL}, NULL}, false, 0, false, 0}
#define MS3KG_App_Light_init_zero                {false, _MS3KG_App_Light_Mode_MIN, false, RGB_init_zero, false, 0, false, 0}
#define MS3KG_App_Magnet_init_zero               {false, _MS3KG_App_Magnet_Mode_MIN}
#define MS3KG_App_System_init_zero               {false, _MS3KG_App_System_Mode_MIN}
#define MS3KG_App_Remote_init_zero               {0}
#define MS3KG_App_Beat_init_zero                 {false, _MS3KG_App_Beat_Mode_MIN, false, 0, false, RGB_init_zero}
#define MS3KG_App_Countdown_init_zero            {false, _MS3KG_App_Countdown_Mode_MIN}
#define MS3KG_App_Arpi_init_zero                 {false, _MS3KG_App_Arpi_Mode_MIN}
#define MS3KG_App_Sequi_init_zero                {false, MIDI_SEQUENCE_init_zero}
#define MS3KG_App_Updater_init_zero              {false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define MS3KG_SysPref_AP_INFO_networkName_tag    1
#define MS3KG_SysPref_AP_INFO_password_tag       2
#define MIDI_INTERVALS_v_tag                     1
#define MIDI_OCTAVE_o_tag                        1
#define MS3KG_App_Arpi_mode_tag                  1
#define MS3KG_App_Countdown_mode_tag             1
#define MS3KG_App_Magnet_mode_tag                1
#define MS3KG_App_Shake_image_tag                1
#define MS3KG_App_Shake_colorIndex_tag           2
#define MS3KG_App_Shake_bounce_tag               3
#define MS3KG_App_System_mode_tag                1
#define MS3KG_App_Updater_shouldReset_tag        1
#define RGB_R_tag                                1
#define RGB_G_tag                                2
#define RGB_B_tag                                3
#define MIDI_STEP_interval_tag                   1
#define MIDI_STEP_octave_tag                     2
#define MIDI_STEP_mode_tag                       3
#define MS3KG_App_Beat_mode_tag                  1
#define MS3KG_App_Beat_sensitivity_tag           2
#define MS3KG_App_Beat_color_tag                 3
#define MS3KG_App_Light_mode_tag                 1
#define MS3KG_App_Light_color_tag                2
#define MS3KG_App_Light_colorIndex_tag           3
#define MS3KG_App_Light_triggerSpeed_tag         4
#define MIDI_SEQUENCE_steps_tag                  1
#define MS3KG_App_Sequi_sequence_tag             1
#define MS3KG_App_current_tag                    1
#define MS3KG_App_shake_tag                      2
#define MS3KG_App_light_tag                      3
#define MS3KG_App_magnet_tag                     4
#define MS3KG_App_system_tag                     5
#define MS3KG_App_remote_tag                     6
#define MS3KG_App_beat_tag                       7
#define MS3KG_App_countdown_tag                  8
#define MS3KG_App_arpi_tag                       9
#define MS3KG_App_sequi_tag                      10
#define MS3KG_App_updater_tag                    11
#define MS3KG_apps_tag                           1

/* Struct field encoding specification for nanopb */
#define RGB_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    R,                 1) \
X(a, STATIC,   REQUIRED, INT32,    G,                 2) \
X(a, STATIC,   REQUIRED, INT32,    B,                 3)
#define RGB_CALLBACK NULL
#define RGB_DEFAULT (const pb_byte_t*)"\x08\xff\x01\x10\x79\x18\x00\x00"

#define MIDI_OCTAVE_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    o,                 1)
#define MIDI_OCTAVE_CALLBACK NULL
#define MIDI_OCTAVE_DEFAULT (const pb_byte_t*)"\x08\x05\x00"

#define MIDI_INTERVALS_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    v,                 1)
#define MIDI_INTERVALS_CALLBACK NULL
#define MIDI_INTERVALS_DEFAULT (const pb_byte_t*)"\x08\x00\x00"

#define MIDI_STEP_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  interval,          1) \
X(a, STATIC,   REQUIRED, MESSAGE,  octave,            2) \
X(a, STATIC,   REQUIRED, INT32,    mode,              3)
#define MIDI_STEP_CALLBACK NULL
#define MIDI_STEP_DEFAULT NULL
#define MIDI_STEP_interval_MSGTYPE MIDI_INTERVALS
#define MIDI_STEP_octave_MSGTYPE MIDI_OCTAVE

#define MIDI_SEQUENCE_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  steps,             1)
#define MIDI_SEQUENCE_CALLBACK NULL
#define MIDI_SEQUENCE_DEFAULT NULL
#define MIDI_SEQUENCE_steps_MSGTYPE MIDI_STEP

#define MS3KG_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  apps,              1)
#define MS3KG_CALLBACK NULL
#define MS3KG_DEFAULT NULL
#define MS3KG_apps_MSGTYPE MS3KG_App

#define MS3KG_SysPref_FIELDLIST(X, a) \

#define MS3KG_SysPref_CALLBACK NULL
#define MS3KG_SysPref_DEFAULT NULL

#define MS3KG_SysPref_AP_INFO_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   networkName,       1) \
X(a, CALLBACK, OPTIONAL, STRING,   password,          2)
#define MS3KG_SysPref_AP_INFO_CALLBACK pb_default_field_callback
#define MS3KG_SysPref_AP_INFO_DEFAULT NULL

#define MS3KG_App_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    current,           1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  shake,             2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  light,             3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  magnet,            4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  system,            5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  remote,            6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  beat,              7) \
X(a, STATIC,   OPTIONAL, MESSAGE,  countdown,         8) \
X(a, STATIC,   OPTIONAL, MESSAGE,  arpi,              9) \
X(a, STATIC,   OPTIONAL, MESSAGE,  sequi,            10) \
X(a, STATIC,   OPTIONAL, MESSAGE,  updater,          11)
#define MS3KG_App_CALLBACK NULL
#define MS3KG_App_DEFAULT NULL
#define MS3KG_App_shake_MSGTYPE MS3KG_App_Shake
#define MS3KG_App_light_MSGTYPE MS3KG_App_Light
#define MS3KG_App_magnet_MSGTYPE MS3KG_App_Magnet
#define MS3KG_App_system_MSGTYPE MS3KG_App_System
#define MS3KG_App_remote_MSGTYPE MS3KG_App_Remote
#define MS3KG_App_beat_MSGTYPE MS3KG_App_Beat
#define MS3KG_App_countdown_MSGTYPE MS3KG_App_Countdown
#define MS3KG_App_arpi_MSGTYPE MS3KG_App_Arpi
#define MS3KG_App_sequi_MSGTYPE MS3KG_App_Sequi
#define MS3KG_App_updater_MSGTYPE MS3KG_App_Updater

#define MS3KG_App_Shake_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   image,             1) \
X(a, STATIC,   OPTIONAL, INT32,    colorIndex,        2) \
X(a, STATIC,   OPTIONAL, INT32,    bounce,            3)
#define MS3KG_App_Shake_CALLBACK pb_default_field_callback
#define MS3KG_App_Shake_DEFAULT NULL

#define MS3KG_App_Light_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    mode,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  color,             2) \
X(a, STATIC,   OPTIONAL, INT32,    colorIndex,        3) \
X(a, STATIC,   OPTIONAL, INT32,    triggerSpeed,      4)
#define MS3KG_App_Light_CALLBACK NULL
#define MS3KG_App_Light_DEFAULT NULL
#define MS3KG_App_Light_color_MSGTYPE RGB

#define MS3KG_App_Magnet_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    mode,              1)
#define MS3KG_App_Magnet_CALLBACK NULL
#define MS3KG_App_Magnet_DEFAULT NULL

#define MS3KG_App_System_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    mode,              1)
#define MS3KG_App_System_CALLBACK NULL
#define MS3KG_App_System_DEFAULT NULL

#define MS3KG_App_Remote_FIELDLIST(X, a) \

#define MS3KG_App_Remote_CALLBACK NULL
#define MS3KG_App_Remote_DEFAULT NULL

#define MS3KG_App_Beat_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    mode,              1) \
X(a, STATIC,   OPTIONAL, INT32,    sensitivity,       2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  color,             3)
#define MS3KG_App_Beat_CALLBACK NULL
#define MS3KG_App_Beat_DEFAULT (const pb_byte_t*)"\x10\x02\x00"
#define MS3KG_App_Beat_color_MSGTYPE RGB

#define MS3KG_App_Countdown_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    mode,              1)
#define MS3KG_App_Countdown_CALLBACK NULL
#define MS3KG_App_Countdown_DEFAULT (const pb_byte_t*)"\x08\x04\x00"

#define MS3KG_App_Arpi_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    mode,              1)
#define MS3KG_App_Arpi_CALLBACK NULL
#define MS3KG_App_Arpi_DEFAULT (const pb_byte_t*)"\x08\x07\x00"

#define MS3KG_App_Sequi_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  sequence,          1)
#define MS3KG_App_Sequi_CALLBACK NULL
#define MS3KG_App_Sequi_DEFAULT NULL
#define MS3KG_App_Sequi_sequence_MSGTYPE MIDI_SEQUENCE

#define MS3KG_App_Updater_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    shouldReset,       1)
#define MS3KG_App_Updater_CALLBACK NULL
#define MS3KG_App_Updater_DEFAULT NULL

extern const pb_msgdesc_t RGB_msg;
extern const pb_msgdesc_t MIDI_OCTAVE_msg;
extern const pb_msgdesc_t MIDI_INTERVALS_msg;
extern const pb_msgdesc_t MIDI_STEP_msg;
extern const pb_msgdesc_t MIDI_SEQUENCE_msg;
extern const pb_msgdesc_t MS3KG_msg;
extern const pb_msgdesc_t MS3KG_SysPref_msg;
extern const pb_msgdesc_t MS3KG_SysPref_AP_INFO_msg;
extern const pb_msgdesc_t MS3KG_App_msg;
extern const pb_msgdesc_t MS3KG_App_Shake_msg;
extern const pb_msgdesc_t MS3KG_App_Light_msg;
extern const pb_msgdesc_t MS3KG_App_Magnet_msg;
extern const pb_msgdesc_t MS3KG_App_System_msg;
extern const pb_msgdesc_t MS3KG_App_Remote_msg;
extern const pb_msgdesc_t MS3KG_App_Beat_msg;
extern const pb_msgdesc_t MS3KG_App_Countdown_msg;
extern const pb_msgdesc_t MS3KG_App_Arpi_msg;
extern const pb_msgdesc_t MS3KG_App_Sequi_msg;
extern const pb_msgdesc_t MS3KG_App_Updater_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define RGB_fields &RGB_msg
#define MIDI_OCTAVE_fields &MIDI_OCTAVE_msg
#define MIDI_INTERVALS_fields &MIDI_INTERVALS_msg
#define MIDI_STEP_fields &MIDI_STEP_msg
#define MIDI_SEQUENCE_fields &MIDI_SEQUENCE_msg
#define MS3KG_fields &MS3KG_msg
#define MS3KG_SysPref_fields &MS3KG_SysPref_msg
#define MS3KG_SysPref_AP_INFO_fields &MS3KG_SysPref_AP_INFO_msg
#define MS3KG_App_fields &MS3KG_App_msg
#define MS3KG_App_Shake_fields &MS3KG_App_Shake_msg
#define MS3KG_App_Light_fields &MS3KG_App_Light_msg
#define MS3KG_App_Magnet_fields &MS3KG_App_Magnet_msg
#define MS3KG_App_System_fields &MS3KG_App_System_msg
#define MS3KG_App_Remote_fields &MS3KG_App_Remote_msg
#define MS3KG_App_Beat_fields &MS3KG_App_Beat_msg
#define MS3KG_App_Countdown_fields &MS3KG_App_Countdown_msg
#define MS3KG_App_Arpi_fields &MS3KG_App_Arpi_msg
#define MS3KG_App_Sequi_fields &MS3KG_App_Sequi_msg
#define MS3KG_App_Updater_fields &MS3KG_App_Updater_msg

/* Maximum encoded size of messages (where known) */
#define RGB_size                                 33
#define MIDI_OCTAVE_size                         11
#define MIDI_INTERVALS_size                      11
#define MIDI_STEP_size                           37
#define MIDI_SEQUENCE_size                       312
/* MS3KG_size depends on runtime parameters */
#define MS3KG_SysPref_size                       0
/* MS3KG_SysPref_AP_INFO_size depends on runtime parameters */
/* MS3KG_App_size depends on runtime parameters */
/* MS3KG_App_Shake_size depends on runtime parameters */
#define MS3KG_App_Light_size                     59
#define MS3KG_App_Magnet_size                    2
#define MS3KG_App_System_size                    2
#define MS3KG_App_Remote_size                    0
#define MS3KG_App_Beat_size                      48
#define MS3KG_App_Countdown_size                 2
#define MS3KG_App_Arpi_size                      2
#define MS3KG_App_Sequi_size                     315
#define MS3KG_App_Updater_size                   11

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
